(define (problem pacientes_trivial)
    (:domain pacientes)
    (:objects  
        hora0 hora1 hora2 hora3 hora4 hora5 hora6 hora7 hora8 hora9 hora10 - Hora
        base enfermeria hab0 hab1 hab2 puerta0 puerta1 puerta2 - Lugar
        paciente0 paciente1 paciente2 - Paciente
    )
    (:init
        (robot_en base)
        (carga_en base)
        (lugar_desinfeccion enfermeria)
        (hora_actual hora0)
        (hora_siguiente hora0 hora1)
        (hora_siguiente hora1 hora2)
        (hora_siguiente hora2 hora3)
        (hora_siguiente hora3 hora4)
        (hora_siguiente hora4 hora5)
        (hora_siguiente hora5 hora6)
        (hora_siguiente hora6 hora7)
        (hora_siguiente hora7 hora8)
        (hora_siguiente hora8 hora9)
        (hora_siguiente hora9 hora10)
        (paciente_en paciente0 hab0)
        (paciente_en paciente1 hab1)
        (paciente_en paciente2 hab2)
        (videollamada_pendiente paciente0 hora3)
        (videollamada_cancelada paciente0 hora3 hora2)
        (videollamada_pendiente paciente1 hora6)
        (videollamada_pendiente paciente2 hora7)
        (videollamada_cancelada paciente2 hora7 hora6)
        (puerta_habitacion puerta0 hab0)
        (puerta_habitacion puerta1 hab1)
        (puerta_habitacion puerta2 hab2)
        (es_habitacion hab0)
        (es_habitacion hab1)
        (es_habitacion hab2)
	(obstaculo_en enfermeria)
        (obstaculo_en puerta0)
        (obstaculo_en hab2)
	(obstaculo_en puerta1)
        (obstaculo_en hab1)
    )
    (:goal
        (and
            (videollamada_terminada paciente0 hora3)
            (videollamada_terminada paciente1 hora6)
            (videollamada_terminada paciente2 hora7)
            (robot_en base)
        )
    )
)